-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 04, 2019 at 05:48 PM
-- Server version: 10.1.36-MariaDB
-- PHP Version: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `techinrumbai`
--

-- --------------------------------------------------------

--
-- Table structure for table `artikel`
--

CREATE TABLE `artikel` (
  `id_artikel` int(11) NOT NULL,
  `judul` varchar(255) NOT NULL,
  `isi` text NOT NULL,
  `gambar` varchar(255) NOT NULL,
  `kategori` varchar(255) NOT NULL,
  `tanggal` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `artikel`
--

INSERT INTO `artikel` (`id_artikel`, `judul`, `isi`, `gambar`, `kategori`, `tanggal`) VALUES
(10, 'Bos Huawei Sebut Hongmeng OS Lebih Cepat dari Android dan MacOS', 'Sejak masuk dalam daftar hitam perdagangan Amerika Serikat, Huawei disebut-sebut sudah menyiapkan sejumlah rencana antisipasi. Salah satunya adalah mengembangkan sistem operasi sendiri mengingat Google selaku pengembang Android sudah memutus hubungan bisnis.  Oleh sebab itu, beberapa bulan terakhir, Huawei santer dilaporkan sedang menyiapkan sistem operasi sendiri yang diberi nama Hongmeng OS. Informasi seputar sistem operasi ini pun sudah kerap diumbar oleh pihak Huawei.Kali ini, informasi terbaru hadir dari founder dan CEO Huawei Ren Zhengfei. Dikutip dari GSM Arena, Minggu (7/7/2019), Zhengfei baru-baru ini ternyata mengungkap performa Hongmeng OS dalam wawancara dengan majalah Prancis.  Menurutnya, Hongmeng OS akan memiliki kemampuan yang lebih cepat ketimbang Android. Tidak hanya itu, sistem operasi ini tidak sekadar digunakan untuk smartphone, melainkan perangkat lain, seperti router, komputer, tablet, bahkan data center.  Zhengfei juga mengklaim Hongmeng OS memiliki kemampuan yang lebih cepat dari MacOS besutan Apple. Dia mengatakan hal itu dimungkinkan sebab sistem operasi ini mampu melakukan pemrosesan kurang dari 5ms.  Zhengfei juga mengatakan bahwa pihaknya tidak akan berhenti mengembangkan Hongmeng, meskipun saat ini pemerintah Amerika Serikat dilaporkan mulai melunak terhadap aturan yang membatasi bisnis Huawei di negara tersebut.', 'hu.jpg', 'smartphone', '2 januari 2019'),
(13, 'Cara Munculkan Notifikasi Ponsel Android di PC Windows 10', 'Aplikasi \"Your Phone\" di sistem operasi PC, Windows 10, sudah meluncur sejak bulan Agustus tahun lalu. Sejak itu, aplikasi ini hanya bisa menampilkan notifikasi SMS dan gambar galeri ponsel yang bisa dilihat dari komputer. Kini, melalui pembaruan \"Your Phone\" teranyar, pengguna bisa melihat notifikasi yang muncul di ponsel Android atau iPhone. Hal itu disampaikan oleh tim Windows di akun resmi Twitter @windowsinsider. Aplikasi \"Your Phone\" sendiri sejatinya didesain untuk mencerminkan data dari ponsel langsung di desktop. Artinya, data seperti SMS, foto, dan pemberitahuan dari ponsel bisa diakses langsung melalui desktop Windows 10. Lantas, bagaimana cara menggunakan aplikasi \"Your Phone\" dan memanfaatkan fitur-fitur yang ada di dalamnya? Cara menggunakan \"Your Phone\" Untuk memanfaatkan fitur ini, pengguna harus mengunduh aplikasi \"Your Phone\" di PC mereka (melalui Windows Store). Selain itu, pengguna juga harus mengunduh aplikasi \"Your Phone Companion\" di smartphone mereka. Setelah diunduh, pengguna kemudian bisa log-in dengan akun Microsoft masing-masing di aplikasi \"Your Phone\" di PC dan juga smartphone mereka. Lalu, Microsoft akan membimbing pengguna step-by-step untuk proses pairing PC dengan ponsel. Ikuti langkah ini dengan seksama.', 'win1.jpg', 'windows', '1 januari'),
(16, 'Harga dan Spesifikasi Galaxy A2 Core, Ponsel Murah Meriah dari Samsung  ', 'Samsung memperkenalkan ponsel murah terbarunya, Galaxy A2 Core. Ponsel peerus Galaxy J2 Core ini menjadi anggota ponsel seri A pertama dari Samsung yang menjalankan operasi Android Go. Galaxy A2 Core memiliki desain dan spesifikasi yang simpel, sesuai segmentasinya yang berbanderol Rp 1,1 jutaan. Ponsel ini juga lebih hemat daya, ruang penyimpanan, serta hemat data berkat Android Go.Galaxy A2 Core memiliki layar berukuran 5 inci dengan resolusi QHD. Punggungnya terbuat dari bahan plastik bernuansa glossy. Secara total, ponsel ini memiliki dua kamera. Satu kamera di depan dengan resolusi 5 megapiksel (f/2.2) dan satu lagi ada di belakang dengan resolusi 5 megapiksel (f/1.9). Selain kamera, di bagian punggung juga dilengkapi LED Flash dan speaker. Galaxy A2 Core ditenagai chip Exynos 7870 octa-core yang dipadu dengan RAM 1 GB dan media penyimpanan internal 8 GB.  Ukuran RAM memang kecil, tapi kinerja ponsel diklaim masih mumpuni. Sebab, aplikasi yang termuat adalah versi lite atau lebih ringan dibanding aplikasi versi Android reguler. Misalnya saja, YouTube Go, Google Go, Gmail Go, Files Go, atau Assistant Go. Dengan ukuran yang mini, otomatis ruang penyimpanan masih longgar dan lebih hemat daya. Selain itu, aplikasi ini juga akan mengonsumsi daya yang lebih sedikit. Di bawah cangkang terbenam baterai berkapasitas 2.600 mAh yang bisa diisi daya dengan konektor micro USB. Android Oreo Go Edition dilapisi antarmuka One UI sebagaimana ponsel Samsung terbaru lainnya. Galaxy A2 Core tersedia dalam tiga warna yakni merah, biru, dan dark grey.  ', '22.jpg', 'smartphone', '2 july 2019'),
(17, 'Samsung Galaxy A80, Unik dengan Kamera Pop-up Bolak-balik', 'Demi menghadirkan layar full sceen, vendor asal Korea Selatan itu menghadirkan kamera pop-up rotating di Samsung Galaxy A80. Sebuah konsep yang belum pernah ada sebelumnya.Namun daya tariknya tidak itu saja. Spesifikasi yang dimiliki ponsel ini mumpuni. Tapi apakah semua itu patut membuatnya patut dimiliki?Desain  Galaxy A80 hadir dimensi yang cukup besar, ukurannya 165.2 x 76.5 x 9.3 mm. Mungkin lantaran membawa mekanisme pop-up rotating camera, membuat ponsel ini terasa lebih berat.   Bobotnya mencapai 220 gram. Pun begitu ponsel ini masih nyaman dioperasikan dengan satu tangan dan disimpan dalam kantong.  Bicara soal tampilannya, kendati masih dalam bagian keluarga Galaxy A, nuansa premium begitu kental terasa. Rasanya tidak jauh berbeda dengan Galaxy S series.Rangka pinggirannya berbahan metal, sementara bodinya berbalut kaca Gorilla Glass 6. Memang bagi tangan yang kerap berkeringat, bikin terasa licin. Tapi dalam paket penjualannya, Samsung menyertakan casing yang cantik.   Sehingga lebih nyaman menggenggam sekaligus memberi perlindungan lebih pada bodi Galaxy A80. Di bagian casing ini terdapat stiker. Bila dibuka bisa makin merekatkan casing dan unit ponsel.  Kalau boleh saran, baiknya tidak perlu dibuka. Karena kamu akan sulit ketika membongkarnya untuk membersihkan bodi belakang, terutama di bagian pop-up.   Seiring penggunaan pastilah ada debu yang menempel. Dengan membersihkannya secara rutin kita dapat mengurangi risiko debu mempengaruhi naik turun kamera. Walaupun, menurut The Verge, Samsung Galaxy telah menguji durabilitasnya dengan melakukan mengetes debu dan rotor perangkat. Tapi tidak ada salahnya kan menjaga ponsel tetap bersih.   Layar Dengan membawa kamera pop-up rotating, membuat layar bebas notch ataupun punch hole. Bentangannya begitu luas tanpa gangguan. Ya walaupun ada bezel di bagian bawah layar tidak begitu mengganggu.  Ukuran layarnya sendiri 6,7 inch dengan resolusi Full HD+. Menggunakan panel Super AMOLED dengan aspek rasio 20:9, memberikan pengalaman sinematik yang memanjakan mata.', 'Samsung-Galaxy-A80-4.jpg', 'smartphone', '3 july 2019'),
(18, 'Samsung Galaxy A60,', 'Dikutip dari laman resmi Samsung pada Minggu (21/7/2019), Galaxy A60 hadir dengan desain layar Infinity O-display.  Terdapat kamera punch hole di bagian pojok kiri atas.  Layar dilengkapi dengan fasilitas Full HD+ yang mendukung penggunanya untuk bermain game, menonton video, dan bermacam kegiatan lainnya.Samsung Galaxy A60 memiliki ukuran layar sebesar 6,3 inci dengan resolusi 2340x1080.  Lalu, ponsel tersebut berdimensi 156.4 x 74.5 x 8.8 dengan berat 168 gram.    ', 'Samsung-Galaxy-A60-2.jpg', 'smartphone', '5 july 2019'),
(19, 'Samsung Galaxy A40,', 'Samsung Galaxy A40 dirilis pada pertengahan Maret 2019.  Dikutip dari Kompas.com, Senin (22/7/2019), Galaxy A40 mengusung desain Infinity-U atau panel Super AMOLED dengan poni kecil berbentuk tetesan air atau waterdrop.  Ukuran layar Galaxy A40 sebesar 5,9 inci dengan resolusi Full HD+1080X2.340 dengan aspek rasio 19,5:9.  Galaxy A40 ditenagai oleh chipset Exynos 7885 dengan prosesor Octa-core (2x1.77 GHz 8 & 6x1.59 GHz) Namun ruang penyimpanan ponsel tersebut dapat diperluas hingga 512 GB.  Dari segi kamera, Galaxy A40 dibekali dengan dua kamera belakang yang masing-masing memiliki sensor 16 megapiksel dan lima megapiksel dengan lensa ultra wide.  Ponsel itu dibekali dengan kamera bersensor 25 megapiksel.    ', 'Samsung-Galaxy-A40-1.jpg', 'smartphone', '6 JULY 2019'),
(20, 'TapCash Gagal Top Up, Ini Penjelasan BNI ', 'Sejak beberapa hari terakhir pengguna atau pemegang kartu BNI TapCash mengeluh kerena ketika transaksi mengisi ulang uang elektronik (top up) gagal. Bahkan saldo rekening mereka ter-debet atau terpotong. Menanggapi itu, Corporate Secretary BNI Meiliana mengatakan, pihaknya meminta maaf kepada semua pengguna atau pemegang kartu BNI TapCash atas ketidaknyamanan tersebut. \"Kami mohon maaf atas ketidaknyamanan yang telah dialami oleh para pengguna TapCash,\" kata Meiliana kepada Kompas.com, Senin (3/6/2019). Dia mengatakan, kegagalan transaksi pengisian uang elektronik di TapCash tersebut biasanya karena jaringan kurang baik. Sehingga proses yang dilakukan costumer menjadi gagal.\"Umumnya penyebab belum ter-update-nya saldo TapCash saat melakukan update saldo via aplikasi TapCashGo karena jaringan komunikasi di sekitar kurang bagus. Apabila melakukan update saldo dalam keadaan bergerak/berkendara, agar dipastikan jaringan komunikasi stabil,\" sebutnya. Meiliana pun menyarankan agar para pengguna yang hendak melakukan pengisian saldo TapCash sebaiknya terlebih dahulu melakukan update saldo melalui ATM ataupun aplikasi TapcashGO. Jika menemukan kendala dalam proses ini segera melapor ke BNI. \"Apabila terjadi kendala dalam melakukan update saldo TapCash, pengguna TapCash dapat menghubungi BNI Call 1500046 dengan menyampaikan Nomor TapCash, saldo rekening yang terdebet, serta saldo akhir TapCash,\" tuturnya. Sebelumnya diberitakan, m-banking perbankan nasional mengalami gangguan. Hal ini juga berdampak pada top up saldo uang elektronik yang diterbitkan bank-bank nasional. Seperti yang dikeluhkan seorang pemegang kartu BNI Tap Cash, Esti. Dia mengeluh kerena ketika transaksi mengisi ulang uang elektronik (top up) gagal. Meskipun transaksi gagal namun saldo dalam rekening terdebet. \"Iya, ada gangguan sehingga top up uang elektronik BNI Tap Cash gagal, namun saldo sudah terpotong,\" katanya, Minggu (2/6/2019). ', 'bni.jpg', 'e-money', '31 februarui 2109'),
(21, 'Sistem Bank Mandiri Error, Top Up E-Money Juga Terdampak.', 'Terjadinya sistem error di Bank Mandiri ternyata tidak hanya berdampak kepada perubahan saldo rekening nasabahnya. Namun menurut Corporate Secretary Bank Mandiri Rohan Hafas, gangguan juga berdampak kepada sistem top up e-money Bank Mandiri. \"Untuk top up e-money itu iya berdampak terhadap sebagain nasabah yang 10 persen itu,\" ujarnya di Jakarta, Sabtu (20/7/2019).Rohan menyebut ada sekitar 10 persen nasabah Bank Mandiri yang terdampak masalah error sistem IT data yang terjadi sejak pagi ini. Error terjadi saat saat perpindahan proses dari core system ke back up system yang rutin dilaksanakan di akhir hari. Meski begitu ia menjamin perubahan yang terjadi dan dampak error system ini akan kembali normal dalam waktu 2 jam ke depan. Bank Mandiri kata dia sudah memiliki data saldo rekening nasabah sehingga tinggal perlu waktu untuk memulihkan kembali normal.  Artikel ini telah tayang di Kompas.com dengan judul \"Sistem Bank Mandiri Error, Top Up E-Money Juga Terdampak\", https://money.kompas.com/read/2019/07/20/130405426/sistem-bank-mandiri-error-top-up-e-money-juga-terdampak.  Penulis : Yoga Sukmana Editor : Erlangga Djumena  Artikel ini telah tayang di Kompas.com dengan judul \"Sistem Bank Mandiri Error, Top Up E-Money Juga Terdampak\", https://money.kompas.com/read/2019/07/20/130405426/sistem-bank-mandiri-error-top-up-e-money-juga-terdampak.  Penulis : Yoga Sukmana Editor : Erlangga Djumena', 'mandiri.jpeg', 'e-money', '21 februari 2019'),
(22, 'Transaksi Uang Elektronik Melesat saat Ramadhan dan Lebaran.', 'Momen Ramadhan dan libur Lebaran 2019 mampu mendongkrak transaksi uang elektronik. Alhasil transaksi non-tunai di perbankan semakin mengalami peningkatan. Transaksi uang elektronik PT Bank Negara Indonesia (Persero) Tbk (KOMPAS100: BBNI) yakni kartu TapCash misalnya melonjak sekitar 30 persen dibandingkan kondisi normal menjadi 132.060 transaksi per hari. \"Sementara rata-rata transaksi kartu TapCash saat kondisi normal sekitar 101.000 per hari.\" ungkap Vice President E-Channel Bank BNI Fajar Kusuma Nugraha pada Kontan.co.id, Selasa (11/6/2019).BNI akan terus berupaya meningkatkan transaksi TapCash dengan memperbanyak akseptasi transaksi. Saat ini, kartu elektronik ini sudah bisa digunakan di seluruh ruas tol, moda transportasi, parkiran, merchant ritel modern, dan penyeberangan Feri (ASDP). Fajar bilang, akseptasi diperluas tahun ini di seluruh merchant EDC BNI, seluruh perparkiran baik operator swasta maupun non swasta, Agen46 dalam mendukung cashless society di Bisnis UMKM, Wahana Entertainment dan tempat akseptasi lainnya. Sampai akhir tahun, BNI menargetkan penjualan kartu TapCash baru bisa mencapai 8 juta. Adapun transaksi ditargetkan mencapai 82 juta transaksi atau meningkat 164 persen dari tahun 2018. Sementara PT Bank Central Asia Tbk (KOMPAS100: BBCA) mencatatkan transaksi uang elektronik lewat kartu Flazz meningkat 53 persen selama bulan Ramadan dan libur lebaran 2019 dibandingkan periode yang sama tahun sebelumnya. Presiden Direktur BCA Jahja Setiaatmadja mengatakan, transaksi Flazz meningkat tajam karena liburan Lebaran tahun ini pemudik banyak menggunakan transportasi pribadi lantaran jalan tol sudah tersambung. \"Selama libur Lebaran, transaksi harian BCA mencapai tertinggi Rp 32 juta, meningkat 25 persen dari tahun lalu yang hanya Rp 27 juta. Dari transaksi itu yang paling menonjol peningkatannya dari kartu Flazz.\" jelas Jahja.', 'tol.jpg', 'e-money', '12 januari 2019'),
(23, 'Dengan LinkAja, Bisa Bayar Tol Tanpa Kartu? ', 'Masalah antre di gerbang tol belum juga teratasi meski sudah mengadopsi sistem pembayaran menggunakan kartu uang elektronik. Untuk mempercepat pembayaran di gerbang tol, platform uang elektronik besutan BUMN, LinkAja sedang melakukan uji coba pembayaran tol tanpa kartu. Ujicoba dilakukan menggunakan Radio Frekuensi Identification (RFID) berupa striker yang ditempel di kaca lampu depan mobil. \"Keunggulan saat masuk gerbang tol, ketika RFID terbaca dalam kecepatan 30 km per jam, palang tol akan terbuka otomatis,\" ujar CMO LinkAja Edward Kilian Suwignyo di Jakarta, Kamis (4/7/2019).Sistem ini mirip dengan On Board Unit e-toll. Namun ungkap Edward, RFID yang ditempel memilki ukuran yang lebih kecil dibandingkan OBU. Selain itu nantinya harga RFID ini akan jauh lebih murah dari OBU. Untuk tahap awal kata Edward, pengguna RFID mengunduh aplikasi FLO. Di sana nantinya pengguna tinggal mendaftarkan nomor RFID-nya. Sementara itu saldo di aplikasi FLO akan berasal dari uang elektronik LinkAja. Bila saldo cukup, maka pembayaran tol tanpa kartu uang elektronik bisa dilakukan di beberapa gerbang tol khusus yang sudah dipasang alat khusus. Baca juga: Begini Cara Bertransaksi lewat LinkAja Sementara pada tahap selanjutnya, nantinya kata Edward pengguna RFID tidak perlu menggunakan aplikasi FLO. Semua bisa diakukan di aplikasi LinkAja. \"Kalau saldo LinkAja ada pasti bisa lewat tol,\" kata dia. Belum diketahui kapan RFID tersebut akan dijual ke publik. Namun saat ini ucap dia, sejumlah gerbang tol sudah dipasang alat pembaca RFID tersebut. Saat ini sudah ada 20 titik gerbang tol yang dipasang alat pembaca RFID tersebut. Hingga akhir tahun ini ucap Edward jumlahnya ditargetkan akan bertambah menjadi 200 titik gerbang tol.  ', 'link.jpeg', 'e-money', '23 Januari 2019'),
(24, 'BI: Kebutuhan Uang Tunai Tinggi Meski Uang Elektronik Populer', 'Bank Indonesia mengumumkan kebutuhan uang pecahan kecil (UPK) tahun ini meningkat 13,5 persen. Peningkatan ini tertinggi sejak 5 tahun terakhir yang pertumbuhan rata-ratanya hanya 13,3 persen.Deputi Gubernur Bank Indonesia Rosmaya Hadi mengatakan hal ini menunjukkan kecenderungan masyarakat dalam menggunakan uang tunai selama periode Lebaran semakin besar. \"Kebutuhan masyarakat terhadap uang tunai di periode Lebaran tahun ini lebih besar dibandingkan dengan tahun-tahun sebelumnya. Meskipun kebutuhan uang elektronik naik, tetapi kebutuhan uang tunai juga naik,\" katanya dalam acara Pembukaan Penukaran Uang Pecahan Kecil (UPK) Taman IRT Monas, Jumat, 17 Mei 2019.    Rosmaya melanjutkan, kenaikan yang lebih tinggi ini juga menunjukkan kepercayaan masyarakat dalam meningkatkan konsumsinya selama periode Idul Fitri juga meningkat.   Adapun, Rosmaya memaparkan jumlah UPK yang dipersiapkan otoritas moneter senilai Rp 217,1 triliun. Pada hari ke-12 ini, BI telah menggelontorkan UPK sekitar Rp 37 triliun.   Permintaan penukaran UPK, lanjutnya akan semakin tinggi mendekati hari-hari terakhir, yakni minggu keempat Mei 2019.Rosmaya melanjutkan, UPK dibagi sesuai dengan kebutuhan di daerah masing-masing, dan setiap bank di daerah tersebut mendapat porsi sesuai dengan proyeksi yang mereka ajukan sebelumnya.   Kebutuhan uang pecahan kecil di Jawa non-Jabodetabek mencapai Rp 84 triliun, Jabodetabek Rp 51,5 triliun, Sumatera Rp 41,2 triliun, dan kawasan timur Indonesia Rp 40,4 triliun.  ', '321.jpg', 'e-money', '22 Maret 2019'),
(25, 'Microsoft Bersiap Akhiri Windows 7', ' Microsoft secara resmi mengakhiri dukungan untuk Windows 7 dalam setahun kedepan yakni 14 Januari 2020. Nantinya Microsoft tak lagi menyediakan dukungan untuk pemilik komputer dan laptop yang masih menggunakan Windows 7.  Dalam situs resminya, Microsoft mengumumkan bahwa pengguna Windows 7 nantinya tak mendapatkan segala bentuk dukungan, termasuk dari serangan malware. Pengguna masih memiliki waktu selama setahun sebelum semua dukungan tak lagi tersedia.  Dengan kata lain, bagi pengguna yang masih memakai Windows 7 maka Microsoft tak memberikan bantuan keamanan dan pembaruan fitur jika nantinya terserang malware.Sebagai gantinya, pengguna bisa beralih menggunakan perangkat baru atau cukup memperbarui peranti lunak dengan Windows 10.  Perusahaan yang berbasis di Redmond, California, AS ini mengatakan pengguna Windows 7, 8, dan 8.1 Pro bisa mendapatkan pembaruan gratis dengan membeli Microsoft 365 Business.  Microsoft sebelumnya telah mengumumkan rencana mengakhiri hidup Windows 7 sejak Januari 2017. Selama tiga tahun terakhir, perusahaan yang didirikan oleh Bill Gates ini telah memberi kesempatan bagi pengguna Windows 7 untuk migrasi ke Windows 10.\"Windows 7 secara perlahan kian usang dan tidak sesuai dengan perkembangan teknologi modern saat ini terutama dari sisi kebutuhan keamanan tingkat tinggi. Kami belajar seharusnya menghentikan dukungan untuk Windows XP lebih awal untuk mengantisipasi kerugian dari sisi biaya dan serangan malware di masa depan,\" tulis Head of Microsoft Jerman, Markus Nitschke saat itu.  Windows 7 pertama kali dirilis pada 2009 silam. Sistem operasi ini merupakan langkah awal Microsoft sebagai penyedia penyimpanan awan (cloud computing). ', '54321.jpeg', 'windows', '22 Mei 2019'),
(26, 'Update Windows 10, Pengguna Tidak Perlu Login Pakai Password', 'Microsoft tampaknya akan segera menghilangkan fitur kata sandi (password) perlahan-lahan.  Dengan update Windows 10 Mei 2019, pengguna Windows 10 versi 1903 bisa login ke gadget, aplikasi dan platform online menggunakan biometrik atau PIN, bukan password.  Ini berarti, pengguna Microsoft Edge, Google Chrome dan Mozilla Firefox bakal login dengan facial-recognition dan sensor fingerprint.  Tak hanya itu, sistem biometrik ini bakal mengijinkan pengguna untuk mengakses program Windows seperti Outlook.com, Office 365, Skype, Xbox Live di PC dan lainnya.Dengan pengguna aktif sekitar 800 juta, dampaknya tentu akan langsung terasa. \"Tidak ada yang menyukai password, kecuali hacker,\" ungkap Yogesh Mehta dari Microsoft, dalam postingan blognya.  Bulan lalu, Microsoft mengungkapkan kebijakan kadaluarsa kata sandi (password expiration policies) tidak berguna dan kemudian membuangnya dari pengaturan dasar keamanan Windows 10 v1903.  Sekarang, Microsoft sedang fokus mengembangkan teknologi untuk menghilangkan password dari seluruh sistem.', '1098.webp', 'windows', '22 Maret 2019'),
(27, 'Pengguna Windows 10 Kini Tak Perlu Ribet Copot Flashdisk', 'Mencabut flashdisk atau flash drive dari PC dan laptop Windows memang membutuhkan sedikit waktu dan effort.  Pasalnya, pengguna harus memilih opsi safely eject sebelum benar-benar mencabut flashdisk dari slotnya.  Namun, kini ada kabar baik bagi semua pengguna Windows yang sudah menggunakan OS Windows 10.Seperti diumumkan Microsoft, mencabut flashdisk dari PC dan laptop yang berjalan dengan Windows 10 versi 1809 tak perlu lagi harus memilih opsi safely eject.  Dilaporkan The Verge, Selasa (9/4/2019), fitur baru ini dinamakan \"Quick Removal\", yang memungkinkan pengguna langsung mencabut flashdisk dari slot PC dan laptop.  Secara teknis, Microsoft sebetulnya sudah menguji coba fitur ini pada Oktober 2018 saat versi 1809 sudah bergulir.  Dan pada akhirnya, Quick Removal kini sudah dirilis ke versi 1809 di seluruh dunia.', '987.webp', 'windows', '21 Maret 2019'),
(28, 'Seperti diumumkan Microsoft, mencabut flashdisk dari PC dan laptop yang berjalan dengan Windows 10 versi 1809 tak perlu lagi harus memilih opsi safely eject.  Dilaporkan The Verge, Selasa (9/4/2019), fitur baru ini dinamakan \"Quick Removal\", yang memungki', 'Pernah mengalami masalah dengan laptop atau PC? Jika ya, sebagian besar dari kamu pasti berusaha menghubungi tim IT di kantor atau membawa perangkat ke tempat servis.  Namun, bagi kamu yang tidak ingin melakukan kedua hal tersebut di atas dan ingin memperbaiki PC atau laptop sendiri, booting komputer Windows dalam Safe Mode mungkin dapat menjadi solusi.  Ada beberapa cara yang bisa dilakukan untuk mem-boot Windows 10 dalam Safe Mode. Perlu diingat, tidak semua masalah di komputer kamu dapat diselesaikan dengan modus ini.Tergantung dengan masalah yang terjadi, ada baiknya bagi kamu untuk membawa perangkat ke seseorang yang ahli atau toko servis resminya.  Tanpa panjang lebar, berikut ini adalah cara yang dapat digunakan untuk masuk ke dalam Safe Mode di Windows 10, sebagaimana dikutip dari laman Ubergizmo, Selasa (16/4/2019).', '564.webp', 'windows', '22 Mei 2019'),
(29, 'Bank India Tak Lagi Gunakan Windows XP', ' Windows XP sudah tidak lagi menerima pembaruan sejak April 2014, tapi belum semua organisasi atau perusahaan memperbarui perangkatnya dengan OS baru. India termasuk salah satu yang baru memutuskan beralih dari Windows XP.  Dilansir Softpedia, Selasa (26/6/2018), India mengeluarkan imbauan kepada semua bank di negara tersebut untuk mengimplementasikan sistem keamanan baru.  Itu artinya, semua bank harus meninggalkan Windows XP sepenuhnya pada Juni 2019.Bank Sentral India, Reserve Bank of India (RBI) melalui sebuah memo pada pekan lalu mengungkapkan bahwa transisi dari Windows XP sampai saat ini berjalan lambat.  Oleh sebab itu, pemerintah ingin melihat upaya transisi lebih besar pada pertengahan Juni 2019.  \"Progres yang lambat di pihak bank dalam mengatasi masalah ini telah dipandang serius oleh RBI. Kerentanan yang timbul dari ATM-ATM bank yang beroperasi pada versi OS lama dan tidak memiliki keamanan, dapat berpotensi merugikan konsumen,\" tulis RBI dalam memonya.  RBI memberikan panduan kepada semua bank tentang langkah-langkah keamanan yang harus dilakukan, mulai dari penggunaan password hingga persentase implementasi OS terbaru yang harus dicapai pada tahun depan.', '908.webp', 'windows', '1 Maret 2019'),
(30, 'Lewati 25 Bulan Masa Pengembangan, Debian 10 Akhirnya Rilis!', 'Membawa beberapa pembaharuan pada dekstop environment Debian 10 membawa pembaharuan pada dekstop environment seperti Gnome 3.22, KDE Plasma 5.8, LXDE, LXQt 0.11, Mate 1.16 dan Xfce 4.12. Selain daripada itu Debian 10 menjadi versi debian yang pertama yang membawa program berbasiskan Rust seperti Firefox, ripgrep, fd, exa dan lainnya. Pada Gnome 3.22 yang dibawa, debian menggunakan Wayland sebagai tipe sesi bawaan.  Mampu terpasang dan berjalan pada komputer ketika Secure-Boot aktif Debian 10 dapat terpasang dan berjalan pada komputer yang mengaktifkan fitur Secure-Boot. Perlu diketahui, biasanya pengguna perlu mematikan fitur Secure-boot terlebih dahulu padahal Secure-Boot sendiri adalah fungsi sekuritas pada komputer yang mencegah memuat kode-kode yang tidak terdaftar serta melindungi dari bootkits dan rootkits pada saat instalasi sistem operasi.  Membawa Linux Kernel 4.19-0.4 Debian 10 ini membawa kernel versi 4.19-0.4 dari sebelumnya versi 4.9.0.3 , kernel versi ini adalah salah satu kernel yang mendapat dukungan jangka panjang (LTS)  AppArmor aktif secara bawaan Debian 10, secara bawaan sudah mengaktifkan fitur bernama AppArmor. Fitur ini sendiri digunakan sebagai kerangka kerja yang mengatur kontrol akses wajib.  NFTables sebagai pengganti IPTables Debian 10 juga membawa NFtables sebagai pengganti iptables yang biasa digunakan untuk mengatur lalu lintas pada jaringan komputer. Dengan adanya NFTables, pengguna dapat mengatur dengan sintaks yang lebih mudah dipahami serta mendapatkan dukungan lebih baik untuk firewall ipv4-ipv6  Tentunya masih banyak pembaharuan lainnya yang dibawa pada Debian 10 ini, untuk lebih lengkapnya, kamu bisa membaca catatan rilis resmi disini.  Tertarik Untuk Menggunakan Debian 10? Jika kamu menginginkan untuk mencoba Debian 10 sekarang, kamu dapat melakukan peningkatan pada repositori package Debian 9 Stretch.', '765.png', 'linux', '22 Maret 2019'),
(31, 'Kernel Linux 5.0.21 Menjadi Rilis Terakhir, Dukungan Kernel Linux Seri 5.0 Dihentikan', 'Dilansir dari milis salah satu pengembang kernel linux yaitu Greg Kroah-Hartman, Beliau secara resmi mengumumkan rilis terakhir kernel linux dari seri 5.0 yaitu versi 5.0.21. Hal ini menandakan bahwa kernel linux untuk seri 5.0 tidak akan lagi mendapatkan pemutakhiran atau penambalan sekuritas.Kernel Linux 5.0 ini sendiri baru saja dirilis sekitar 2 bulan yang lalu yaitu pada 4 Maret 2019 oleh Linuz Torvalds dan bukan menjadi bagian dari dukungan jangka panjang yang didukung oleh para pengembang kernel linux. Kernel ini sendiri juga hadir dengan tidak membawa perubahan yang mayor pada pemutakhirannya.  Greg Kroah-Hartman melalui pengumuman milisnya, mendesak agar pengguna aktif kernel linux 5.0 agar segera melakukan pemutakhiran ke versi kernel linux yang lebih baru dan stabil yaitu Kernel linux 5.1Lakukan Peningkatan ke Kernel Linux versi 5.1 Jika anda menggunakan distro GNU/Linux yang ditenagai oleh kernel linux seri 5.0, anda harus melakukan pemutakhiran sekarang ke versi kernel linux 5.0.21 dan mempertimbangkan untuk melakukan peningkatan pada kernel anda ke versi terbaru 5.1. (versi terbaru 5.1.7 pada saat artikel ini ditulis) di hari hari kedepan.  Terdapat 2 cara untuk melakukan peningkatan pada kernel anda, salah satunya adalah dengan mengunduh dan melakukan kompil sumber kode dari kernel.org atau dengan memasang paket binari dari repositori perangkat lunak yang disediakan oleh distro GNU/Linux yang anda gunakan. Harap pastikan anda melakukan hal ini ketika anda telah membaca artikel ini.', '530.jpg', 'linux', '22 Mei 2019'),
(33, 'Penjualan Anjlok, Harga VGA Bakal Turun Sebentar Lagi?', 'Beberapa bulan terakhir ini, untuk merakit sebuah PC gaming sepertinya harus dipikirkan dua kali, terutama dalam pembelian komponen. Khususnya untuk komponen yang paling krusial, yaitu kartu grafis mumpuni untuk memainkan game-game kekinian yang sangat sulit untuk dicari stoknya. Sekalipun ada, harganya pasti diluar batas ekspetasi. Berencana untuk merakit sebuah PC gaming dalam waktu dekat? Jika iya, ada sedikit kabar gembira nih untuk kamu. Baru-baru ini, DigiTimes telah melaporkan bahwa saat ini banyak manufaktur kartu grafis seperti Gigabyte, MSI dan TUL (PowerColor) yang mengungkapkan bahwa penjualannya anjlok sampai menyentuh angka 40% pada bulan April 2018 lalu. Tentunya hal ini bukan tanpa alasan. Para miner yang biasanya menggunakan kartu grafis untuk menambang Ethereum sedang menunggu sebuah alat yang disebut ASIC buatan Bitmain.Alat tersebut dikatakan akan lebih optimal dibanding menggunakan kartu grafis yang sebetulnya diperuntukkan untuk gaming. Tidak bisa dipungkiri lagi kalau Ethereum adalah salah satu cryptocurency favorit para penambang.  Belakangan ini fenomana \"mining\" sedang marak terjadi. Sayangnya, hal tersebut juga memberikan dampak negatif kepada para gamer. Bagaimana tidak, kebanyakan dari mereka para miner, masih hobi menambang menggunakan kartu grafis yang sebenarnya diperuntukkan untuk para gamer. Semoga saja tren positif (bagi para gamer) ini akan terus berlanjut dan harga akan benar-benar turun sesuai dengan harga awal dan para gamer akhirnya berfikir kembali untuk merakit sebuah PC gaming.', '51.jpg', 'vga', '22 Maret 2019'),
(34, 'Banyak VGA Palsu Beredar, Kini Software GPU-Z Bisa Deteksi VGA Palsu', 'Ketika sebuah merakit PC gaming, tentu saja ekspetasi penggunanya adalah bisa memainkan berbagai game kekinian. Salah satu komponen yang paling pentung untuk menunjangnya adalah VGA aka kartu grafis. Namun sayangnya, hal tersebut dimanfaatkan oleh beberapa oknum yang tidak bertanggung jawab.Dilansir dari TweakTown, saat ini kartu grafis palsu sudah mulai banyak beredar di berbagai situs e-commerce seperti eBay. Contohnya saja kartu grafis GTX 1050 Ti yang dijual hampir setengahnya, padahal kartu grafis tersebut sebenarnya adalah GT 730 atau GTX 750 Ti yang biosnya dimodifikasi oleh oknum.Namun kamu tak perlu begitu khawatir, cara membedakannya sebenarnya cukup simple, karena kalau harga yang ditawarkan sangat mirip kemungkinan besar adalah palsu. Selain itu, software ternama GPU-Z saat ini sudah bisa mendeteksi kartu grafis palsu dengan tulisan \"FAKE\" ketika kamu membuka software tersebut.Jadi, buat kamu yang memang sedang mencari kartu grafis untuk segera memainkan game terkini, lebih baik jangan terlalu nafsu dan membelinya kepada penjual yang memang sudah terpercaya reputasinya.', '52.jpg', 'vga', '22 Mei 2019'),
(35, 'Stok Menipis, Kemungkinan Harga VGA Gaming Akan Naik Lagi!', 'Tidak bisa dipungkiri lagi kalau saat ini Cryptocurrency sedang mengalami pelonjakan yang membuat para miner diseluruh dunia semakin giat menambang dan bahkan melahirkan bibit-bibit baru miner yang ingin mencari keuntungan hanya dengan duduk manis di depan komputer saja. Tapi ternyata, bukan hanya itu penyebab kelangkaan VGA aka kartu grafis saat ini.Dilansir dari Digitimes (via Wccftech), kartu grafis NVIDIA GeForce GTX 10 series yang akan paling terkena imbasnya mulai bulan ini, mulai dari GTX 1050 hingga GTX 1080 Ti. Pihak NVIDIA sendiri mengatakan bahwa hal tersebut dikarenakan pasokan memori GDDR5 tersendat sehingga mereka tidak bisa memproduksi secara berlebih, padahal permintaan saat ini sedang membludak.Samsung dan SK Hynix yang dikenal sebagai manufaktur memori GDDR5 sudah tidak berfokus pada kartu grafis desktop saja tetapi juga membuat teknologi RAM standar untuk mengatasi meningkatnya permintaan dari pasar enterprise dan mobile. Untuk kartu grafis AMD sendiri mungkin yang akan paling terkena imbasnya adalah varian RX 460 sampai dengan RX 580 yang masih menggunakan memori GDDR5, sementara varian terbaru RX Vega sudah menggunakan HBM2. Peningkatan harga ini diperkirakan akan meningkat sebesar 10 persen. Stok menipis, sementara permintaan semakin membludak, tidak menutup kemungkinan tren harga VGA gaming naik ini akan terus terjadi sepanjang tahun 2017.', '53.jpg', 'vga', '22 Maret 2019'),
(36, 'Pria Habiskan Rp 142 Juta Buat Service Macbook, Ternyata Masalahnya Cuma Ini', 'Pernah mengalami kerusakan laptop sampai harus merogoh kocek dalam? Pasti menyebalkan, tapi mau tidak mau harus diganti karena kerusakannya memang parah.Tapi bagaimana jadinya kalau kamu harus bayar mahal buat masalah laptop yang sebenarnya sangat sepele?Dilansir 9to5 Mac, Jumat (14/6/2019), salah seorang fotografer dan pengembang bernama Greg Benz curhat kalau Macbook miliknya ngeblank.Saat dinyalakan, kipas laptop berbunyi tapi layarnya tetap gelap. Was-was, Benz kemudian memboyong laptopnya ke toko Apple.Benz bercerita, di toko Apple dia mendapatkan penggantian motherboard hingga dua kali namun tetap tidak menuntaskan masalah. Bahkan, dirinya sampai diberikan laptop baru.Benz sampai menunggu dua minggu dan menghabiskan setidaknya USD 10 ribu atau Rp 142 juta garansi Apple yang terdiri dari dua logic boards, kabel-kabel baru, dan penggantian komputer hingga lebih dari USD 7 ribu atau sekitar Rp 99 juta.', '54.jpg', 'machintos', '23 maret 2019'),
(37, 'Selain iPad dan Mac Baru, Apple Juga Bakal Umumkan Ini?', 'Berselang satu bulan setelah Apple memperkenalkan tiga iPhone terbaru dan juga Apple Watch, perusahaan akhirnya mengumumkan untuk kembali mengadakan acara khusus pada 30 Oktober 2018.  Dari poster yang dirilis secara resmi oleh Apple, tidak tersirat apapun soal jenis perangkat yang akan dirilis.Namun sudah ada prediksi soal perangkat apa yang akan diumumkan di acara yang dihelat di Brooklyn Academy of Music, New York City, Amerika Serikat (AS), tersebut.  Berdasarkan informasi yang dilansir dari Phone Arena, Rabu (23/10/2018), berikut deretan gadget canggih yang kemungkinan besar akan dirilis Apple pada acara 30 Oktober mendatang.  iPad Pro Terbaru  Sudah satu setengah tahun, tepatnya sejak Juni 2017, iPad Pro diperkenalkan.Dengan dirilisnya generasi iPhone XS dan XR yang kini tak memiliki tombol home, sudah pasti lini iPad terbaik ini akan mendapat pemutakhiran. Kabarnya, iPad Pro generasi terbaru akan hadir tanpa bezel tebal, mengusung sistem operasi iOS 12, dan juga dilengkapi dengan Face ID.', '55.jpg', 'machintos', '22 Maret 2019'),
(43, 'Resmi Meluncur, Prosesor Pertama Generasi 10 Intel Diberi Julukan Ice Lake', 'Setelah lama berkutat dengan proses berfabrikasi 14 nm, akhirnya Intel meluncurkan 11 prosesor dari seri Intel Core Generasi ke-10 yang terbaru dan paling terintegrasi, serta didesain untuk perangkat 2-in-1 dan laptop.  Berdasarkan keterangannya, Jumat (2/8/2019), jajaran prosesor tersebut menghadirkan kecerdasan buatan (AI) berperforma tinggi pada PC, beserta fitur grafis baru Intel Iris Plus guna mendukung aktivitas hiburan, serta memampukan konektivitas  terbaik dengan memadukan Intel Wi-Fi 6 (Gig+) dan Thunderbolt 3.  Adapun, prosesor Intel Core Generasi ke-10 dikatakan menjadi pijakan penting bagi perjalanan Intel dalam mendukung peningkatan performa PC terbaik melalui prosesor berkinerja tinggi dan optimal di segala lini komputasi.  Selain performa dan kemampuan respon yang cepat, fitur AI, grafis, konektivitas dan I/O yang teroptimisasi pada SoC menyediakan sebuah solusi dengan berbagai macam kapabilitas yang memampukan OEM untuk menciptakan laptop yang memenuhi beragam kebutuhan, mulai dari baik hiburan, gaming, hingga konten kreator.', '0.63794100-1564794031-intel_211135_big.jpg.jpeg', 'processor', '24 april 2019'),
(45, 'Huawei Klaim Prosesor Kirin 980 Lebih Gesit Ketimbang Apple A12', 'Kompetisi antar perusahaan teknologi--khususnya pembesut smartphone--memang terbilang sengit.  Huawei dan Apple ambil contoh. Belum lama ini, Huawei mengklaim kalau prosesor terbaru besutannya, Kirin 980, punya performa lebih ngebut ketimbang Apple A12.  Padahal, kedua prosesor tersebut dirancang menggunakan prosesor 7 nanometer. Dilansir Ubergizmo, Selasa (25/9/2018), di atas kertas prosesor Apple A12 cukup diragukan karena memiliki inti dan kecepatan clocking yang lebih sedikit.  Namun pada hasil pengujian benchmark, prosesor bionic ini nyatanya mencetak performa yang mengagumkan.  Pada sisi lain, Huawei dengan prosesor Kirin 980 percaya diri kalau mereka benar-benar bisa menaklukkan Apple A12.  Perusahaan mengklaim, mereka telah merancang Kirin 980 selama tiga tahun dengan lebih dari 6,9 miliar transistor.  \"Kirin 980 akan hadir di Mate 20. Prosesor ini 75 persen lebih cepat dari generasi CPU sebelumnya, 46 persen lebih ngebut dari GPU sebelumnya, dan memiliki keseimbangan daya 57 persen lebih baik,\" ujar Huawei.', 'huawei.jpg', 'processor', '29 april 2019'),
(46, 'Intel Luncurkan Prosesor Gaming Terbaik di Dunia', ' Intel meluncurkan jajaran prosesor desktop terbarunya dari keluarga Core generasi ke-9, termasuk Core i9-9900K yang diklaim sebagai prosesor gaming terbaik di dunia.  Jika melihat spesifikasinya, wajar jika Intel berani mengklaim Core i9-9900K sebagai prosesor gaming terbaik di dunia. Prosesor ini mempunyai delapan core dan 16 thread, dengan kecepatan standar 3,6 GHz yang bisa digenjot hingga 5 GHz.  Selain Core i9, Intel juga merilis Core i5 dan Core i7 generasi ke-9. i7-9700K punya empat core dan 8 thread, dengan kecepatan standar 3,6GHz dan 4,9GHz saat di-boost. Sementara i5-9600K punya enam core dan enam thread dan punya kecepatan standar 3,7 GHz yang bisa digenjot hingga 4,6GHz.  Perlu diingat, meski ini adalah prosesor generasi terbaru, Intel masih mengandalkan pabrikasi 14nm di jajaran prosesor ini, sama seperti prosesor generasi ke-5 berkode Broadwell yang dirilis pada 2014. Baca juga: Acer Hadirkan Predator Helios 500 Versi AMD Generasi Kedua   Intel menyebut prosesor generasi ke-9 ini dibuat dengan pabrikasi 14nm++, sama seperti prosesor generasi ke-8 alias Coffee Lake. Intel sendiri masih menunda kehadiran prosesor Cannon Lake yang diproduksi dengan pabrikasi 10nm hingga 2019 mendatang.  Prosesor generasi ke-9 ini juga adalah prosesor desktop pertama yang sudah mendapat perbaikan dari masalah Meltdown Varian 3 dan L1 Terminal Fault, demikian dikutip detikINET dari The Verge, Selasa (9/10/2018).  Soal harga, Intel mematok harga USD 488 untuk Core i9-9900K, USD 373 untuk i7-9700K, dan USD 262 untuk i5-9600K. Prosesor ini sudah bisa dipesan hari ini, dan mulai dikapalkan pada 19 Oktober mendatang.', 'intel.jpeg', 'processor', '1 mei 2019'),
(47, 'Gaming Mouse Razer Viper Unggulkan Optical Switch yang Inovatif', 'Mencari sebuah gaming mouse yang sempurna itu sulit, sebab semuanya kembali bergantung pada preferensi masing-masing konsumen. Sebagian mungkin lebih sreg dengan mouse yang dilengkapi sistem manajemen berat, sedangkan sebagian lainnya justru mendambakan mouse dengan bobot seringan mungkin demi mengakomodasi gaya bermainnya.  Razer baru saja menyingkap suguhan anyar untuk tipe konsumen yang kedua ini. Dijuluki Razer Viper, bobot mouse ini hanya berkisar di angka 69 gram, jauh di bawah mouse gaming lain pada umumnya, sehingga pengguna Viper semestinya bisa lebih cepat bereaksi ketimbang pemain lain.  Bobot yang ringan tentu bukan satu-satunya fitur unggulan mouse berwujud ambidextrous ini. Viper juga menjadi mouse pertama yang mengemas Razer Optical Switch, yang diklaim menawarkan aktuasi hingga tiga kali lebih cepat ketimbang switch mekanis biasa.  Razer menjelaskan bahwa pada mouse tradisional, sinyal input akan dikirim ke komputer setelah switch mekanisnya bersentuhan dengan sebuah pelat logam. Kontak fisik ini seringkali berujung pada beberapa klik ekstra yang tak disadari, namun driver yang tertanam pada mouse cukup pintar untuk mengaktifkan efek debounce delay sehingga komputer membaca hanya ada satu klik yang terjadi.', 'mouse.jpg', 'komputergear', '12  februari 2019'),
(48, 'Gaming Gear Razer Kini Hadir Pula Dengan Monitor, Raptor 27 144Hz Sajian Utamanya', 'Razer tampaknya siap memberikan pilihan produk gaming gear terbaru, dan kali ini mereka akan menyajikan produk yang benar-benar fresh, yakni sebuah monitor gaming dimana mereka menyebutnya sebagai Razer Raptor 27.  Perangkat tersebut bisa menjadi pilihan hebat berikutnya dengan banyak fitur unggulan, apalagi Razer pada dasarnya cukup populer untuk urusan peripheral gaming, meskipun kehadiran lini produk monitor merupakan pertama kalinya dalam sejarah perusahaan asal Amerika tersebut. Kehadiran Razer untuk pasar monitor tentu akan menambah semarak dunia gaming jauh lebih lengkap, apalagi mereka membawa segudang fitur unggulan pada Raptor 27 tersebut, yakni panel IPS dengan tingkat refresh rate 144Hz, bezel ultra-tipis dan waktu respons 1 ms yang sangat cepat. Sedangkan untuk urusan konektivitas, monitor ini akan menawarkan berbagai port input yang cukup lengkap  untuk berbagai perangkat, termasuk 1 x HDMI, 1 x DisplayPort, 1 x USB-C yang mencakup pengiriman daya, dan 2 x USB-A 3.1 port.  Razer Raptor bertujuan untuk meningkatkan produktivitas pengguna dengan kemampuan input gambar-dalam-gambar dan gambar-demi-gambar yang memungkinkan banyak input ditampilkan secara bersamaan. Port USB-C juga termasuk pengiriman daya untuk memungkinkan perangkat dengan watt lebih rendah untuk diisi daya saat terhubung ke monitor.', 'Razer-Gaming-Monitor-feat.jpg', 'komputergear', '28 maret 2019'),
(49, 'Xbox One is getting mouse and keyboard support as Microsoft partners with Razer', 'Razer BlackWidow Elite mungkin bisa dikatakan sebagai salah satu bagian dari keluarga terbaru Gaming Gear Terbaru Razer yang populer, The Blackwidows Series. Dan untuk menyempurnakan produk ini, mereka menghadirkan keyboard dengan switch mekanis milik Razer, yang tersedia dalam warna hijau, oranye dan kuning. Itu berarti bahwa level baru dari gaming keyboard yang berkelas bisa terlihat, atau setidaknya juga akan bersinar dengan kehadiran fitur RGB backlighting yang dapat disesuaikan, 10 tombol anti-ghosting, tombol yang dapat diprogram sepenuhnya dengan dukungan makro, dial digital multi-fungsi, tombol media khusus dan USB 2.0 dan audio pass. BlackWidow Elite juga merupakan yang pertama dari lininya yang menampilkan memori on-board hibrida dan sistem penyimpanan cloud. Karena, model sebelumnya memaksa para gamer untuk menyimpan profil ke cloud melalui perangkat lunak Razerâ€™s Synapse. Meskipun BlackWidow Elite mempertahankan fitur itu, keyboard sekarang juga masih bisa menyimpan hingga lima profil secara lokal sehingga gamer dapat membawa profil ke mana pun mereka pergi. BlackWidow Elite sudah tersedia sejak akhir agustus dengan nilai harga $ 169,99 atau sekitar 2.4 jutaan.', 'keyboard.jpg', 'komputergear', '2 april 2019');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `artikel`
--
ALTER TABLE `artikel`
  ADD PRIMARY KEY (`id_artikel`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `artikel`
--
ALTER TABLE `artikel`
  MODIFY `id_artikel` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=50;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
